Song.create!(name: "Thang dien", singer: "JustaTee, Phuong Ly", rating: 1.2)
Song.create!(name: "Cang niu giu cang de mat", singer: "Mr Siro", rating: 2.3)
Song.create!(name: "Hongkong1", singer: "Nguyen Trong Tai, San Ji, Double X", rating: 3.0)
Song.create!(name: "Vo tinh", singer: "Xesi, Hoaprox", rating: 4.5)
Song.create!(name: "Tan cung noi nho", singer: "Will", rating: 5.8)
Song.create!(name: "Thang dien", singer: "JustaTee, Phuong Ly", rating: 1.7)
Song.create!(name: "Cang niu giu cang de mat", singer: "Mr Siro", rating: 2.6)
Song.create!(name: "Hongkong1", singer: "Nguyen Trong Tai, San Ji, Double X", rating: 3.9)
Song.create!(name: "Vo tinh", singer: "Xesi, Hoaprox", rating: 4.4)
Song.create!(name: "Tan cung noi nho", singer: "Will", rating: 5.1)
